"""Venice verifier verdict parity, built from a locally constructed fixture.

The shared vectors in ``attestation.json`` already pin Venice verdicts across both
languages. This suite is the independent second opinion: it builds its own
self-consistent Venice attestation with Python's own crypto stack rather than
replaying evidence generated by the JavaScript package, so a fixture generator bug
cannot make both sides agree on the wrong answer. It asserts the fail-closed
contract:
  valid          -> status "ok",     verification_level "provider-attested"
  tampered nonce -> status "failed",  reason "nonce_binding"

It also proves the verifier NEVER emits "hardware-verified".
"""

from __future__ import annotations

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

from anonrouter_confidential.crypto.venice import eth_address_from_pub
from anonrouter_confidential.verify import verify_raw_evidence
from anonrouter_confidential.verify.types import AttestationExpectations

_UPSTREAM_MODEL = "venice-uncensored"
_NONCE = "a1b2c3d4e5f6071829384756a1b2c3d4e5f6071829384756a1b2c3d4e5f60718"  # 64 hex


def _build_quote(report_data: bytes) -> str:
    """Assemble a minimal TDX v4 quote (hex) with a chosen 64-byte report_data,
    Intel tee_type, and TD debug disabled."""
    buf = bytearray(632)
    buf[0:2] = (4).to_bytes(2, "little")  # version
    buf[4:8] = (0x81).to_bytes(4, "little")  # teeType (Intel TDX)
    # td_attributes @168 left all-zero -> debug disabled.
    buf[184:232] = bytes(range(48))  # mrTd (arbitrary)
    buf[232:280] = b"\x01" + bytes(47)  # mrConfigId (Venice does not gate on this)
    buf[376:424] = bytes([0xAA]) * 48  # rtmr0
    buf[424:472] = bytes([0xBB]) * 48  # rtmr1
    buf[472:520] = bytes([0xCC]) * 48  # rtmr2
    buf[520:568] = bytes([0xDD]) * 48  # rtmr3
    assert len(report_data) == 64
    buf[568:632] = report_data
    return buf.hex()


def _valid_payload() -> dict:
    priv = ec.derive_private_key(0x9911AABBCCDDEEFF00112233445566778899AABBCCDDEEFF0011223344556677, ec.SECP256K1())
    pub_hex = priv.public_key().public_bytes(Encoding.X962, PublicFormat.UncompressedPoint).hex()
    address = eth_address_from_pub(pub_hex)  # 0x + 40 hex, lowercase
    # report_data[0:32] = 20-byte address || 12 zero bytes; [32:64] = 32-byte nonce.
    first = bytes.fromhex(address[2:]) + bytes(12)
    report_data = first + bytes.fromhex(_NONCE)
    quote_hex = _build_quote(report_data)
    report_data_hex = report_data.hex()
    return {
        "intel_quote": quote_hex,
        "nvidia_payload": "nvidia-gpu-evidence-blob",
        "nonce": _NONCE,
        "model": _UPSTREAM_MODEL,
        "signing_algo": "ecdsa",
        "signing_public_key": pub_hex,
        "signing_address": address,
        "attestation": {
            "report_data": report_data_hex,
            "evidence": {"quote_report_data": report_data_hex},
            "workload_keyset": {
                "e2ee_public_keys": [
                    {"algo": "secp256k1-aes-256-gcm-hkdf-sha256", "public_key": pub_hex}
                ]
            },
        },
    }


def _expectations() -> AttestationExpectations:
    return AttestationExpectations(
        provider="venice",
        upstream_model=_UPSTREAM_MODEL,
        endpoint_identity="venice.example",
        nonce=_NONCE,
        privacy_modality="e2ee",
        measurement_policy=None,
    )


def test_venice_valid_verdict() -> None:
    verdict = verify_raw_evidence("venice", _valid_payload(), _expectations())
    assert verdict.status == "ok", verdict.reason
    assert verdict.verification_level == "provider-attested"
    assert verdict.privacy_modality == "e2ee"
    assert verdict.attested_signing_key is not None
    assert verdict.supports_client_opaque_e2ee is True
    # The verifier must never fabricate a hardware-verified claim.
    assert verdict.verification_level != "hardware-verified"


def test_venice_tampered_nonce_fails_closed() -> None:
    payload = _valid_payload()
    # Corrupt the quote's report_data nonce region (bytes 32:64) but keep the nested
    # attestation report_data consistent with the corrupted quote, so ONLY the nonce
    # binding fails.
    quote = bytearray(bytes.fromhex(payload["intel_quote"]))
    quote[568 + 32 : 568 + 64] = bytes([0xEE]) * 32
    tampered_report_data = bytes(quote[568:632])
    payload["intel_quote"] = quote.hex()
    payload["attestation"]["report_data"] = tampered_report_data.hex()
    payload["attestation"]["evidence"]["quote_report_data"] = tampered_report_data.hex()

    verdict = verify_raw_evidence("venice", payload, _expectations())
    assert verdict.status == "failed"
    assert verdict.reason == "nonce_binding"
    assert verdict.verification_level == "unverified"


def test_unknown_provider_fails_closed() -> None:
    verdict = verify_raw_evidence("bogus", {}, _expectations())
    assert verdict.status == "failed"
    assert verdict.verification_level == "unverified"
    # Matches the JavaScript package: reason "provider_not_verifiable", version "sdk/1".
    assert any(c.detail == "provider_not_verifiable" for c in verdict.checks)
    assert verdict.verifier_version == "sdk/1"
